### ISSUE TITLE
Display moon icon for dark mode on initial launch 

### ISSUE THREAD

**Issue by alyssa-palencia** [zeferinix/atelier-ryza-bottle-password-finder#6]
## Current Behavior
Display mode icon shows sun instead of moon when website is in dark mode.

![image](https://user-images.githubusercontent.com/40421344/228496062-913592f6-30ea-47bc-ab9d-8d03cab54ebd.png)

## Expected Behavior
It should display the moon icon.

**Comment by cerinoligutom** [comment]
Will look into this, have an idea why this is happening.
